 # app 
set(HELLO_WORLD_APP 0)
set(TEST1_APP 0)
set(STRUCTURE_APP 0)
set(UART_COMMUNICATION_APP 0)
set(NET_COMMUNICATION_APP 0)
set(HTTPD_APP 0)
set(HTTP_CLIENT_APP 0)
set(PWM_OUTPUT_APP 0)
set(LED_TEST_APP 0)
set(MODUBUS_APP 0)
set(ENIC_APP 0)
set(CHAT_SERVER_APP 0)
set(MYSQL_ACCESS_APP 0)

#qt app
set(QT_APP 0)
set(QT_HELLO_WORLD_APP 0)

