#ifndef __TX_H
#define __TX_H

#include "stdbool.h"
#include "job.h"

#define TX_DONE                 (1 << 7)
#define TX_MAX_DESC_PER_PKT     (16)

#define GMAC_TXDES0_FTS         (1 << 18)
#define GMAC_TXDES0_LST         (1 << 17)

/* one TSO packet can has 128 children frames at max,  */
#define TX_FRAME_INFO_NUM       ((NIC_SHADOW_TXDESC_PER_QUEUE + 4) * NIC_QPAIR_NUM)
#define TX_FRAME_SEG_INFO_NUM   (96 * NIC_QPAIR_NUM)

typedef struct
{
    uint32_t desc0;
    uint32_t desc1;
    uint32_t desc2;
    uint32_t desc3;
    uint32_t desc4;
    uint32_t desc5;
    uint32_t desc6;//MotherInfo
    uint32_t desc7;
    uint32_t desc8;//IPsec Info
    uint32_t desc9;//IPsec encoding list
    uint32_t desc10;
} TX_DescTypeDef;

typedef struct TX_SegInfo
{
    uint32_t segLen;
    uint32_t offset;
    TX_DescTypeDef *motherDesc;
    struct TX_SegInfo *nextSeg;
} TX_SegInfoTypeDef;

typedef struct
{
    uint8_t payload[NIC_PBUF_LEN];
} PBUF_TypeDef;

typedef struct TX_FrameInfo
{
    uint32_t segNum;
    uint32_t frameLen;
    PBUF_TypeDef *pBuf;
    TX_SegInfoTypeDef *segList;
    struct TX_FrameInfo *nextframe;
} TX_FrameInfoTypeDef;

typedef struct 
{
    /* record how many kids descriptors are generated by this shadow descriptor */
    int32_t frameNum;
    int32_t frameParsedNum;
    int32_t frameReadyNum;
    int32_t frameSentNum;
    int32_t frameFlushedNum;
    /* record how many kids descriptors are in use on GMAC ring */
    int ref;

    TX_DescTypeDef *lastParsedDesc;
    int32_t lastParsedDescOffset;

    TX_FrameInfoTypeDef *frameList;
} TX_MotherInfoTypeDef;

typedef struct
{
    TX_MotherInfoTypeDef MotherInfo[NIC_SHADOW_TXDESC_PER_QUEUE];
} TX_DescBackTraceTypeDef;

bool TX_IsTSO(TX_DescTypeDef *desc);
bool TX_IsIPsec(TX_DescTypeDef *desc);
bool TX_IsGMACRingFull(int gmac, int qid);
bool TX_IsPipelineRunning(int gmac, int qid);
bool TX_IsEncDonePktInQueue(int gmac, int qid);
int TX_GetDmaChannel(int gmac, int qid);
TX_MotherInfoTypeDef* TX_GetMotherInfo(int gmac, int qid, TX_DescTypeDef *desc);
bool TX_DescNeedFetch(int gmac, int qid);
bool TX_DescCanFetch(int gmac, int qid);
bool TX_IsDescNeedFlush(int gmac, int qid);
void TX_PktEnqueue(LIST_HeadTypeDef *listHead, TX_DescTypeDef *desc);
void TX_PktDequeue(LIST_HeadTypeDef *listHead, TX_DescTypeDef *desc);
TX_DescTypeDef *TX_GetNextShadowDesc(int gmac, int qid, TX_DescTypeDef *desc);
int TX_ParseMappingInfo(int gmac, int qid, TX_DescTypeDef *firstDesc);
int TX_FillDMARing(int gmac, int qid, TX_MotherInfoTypeDef *mi);
int TX_RequestIPsecEnc(int gmac, int qid, TX_MotherInfoTypeDef *mi);
int TX_GetPktSegNum(int gmac, int qid, TX_DescTypeDef *firstDesc);
int TX_GetPktSegLen(TX_DescTypeDef *Desc);
int TX_GetPktLen(int gmac, int qid, TX_DescTypeDef *firstDesc);
TX_DescTypeDef* TX_GetNTSDesc(int gmac, int qid);
int TX_FetchDesc(int gmac, int qid);
int TX_FetchData(int gmac, int qid);
int TX_FlushDesc(int gmac, int qid);
int TX_CalcToFetchedDescNum(int gmac, int qid);
int TX_CalcToFlushDescNum(int gmac, int qid);
void TX_CleanShadowDesc(int gmac, int qid);
int TX_SendPkt(int gmac, int qid, TX_MotherInfoTypeDef *mi);
void TX_NextStep(int gmac, int qid, JOB_TypeDef *currentJob);
#endif
